### ISSUE TITLE
Maze: Impossible level is actually not possible to win

### ISSUE THREAD

**Issue by thaeli** [AEFeinstein/Swadge-Devkit-Fw#108]
**Expected Behavior**
Impossible renders a very sense but solvable maze.

**Actual Behavior**
Impossible renders as a blank playfield that cannot be completed, either manually or on automatic.

**Steps To Reproduce or What You Were Doing**
Always occurs on Impossible level. Other difficulties are fine.

**Logs, Pictures, or Video**

**Comment by AEFeinstein** [comment]
Revisions to look at:
* 7d893bbcb98c289ae3eaee6d782f24c79c3882d9
* aacb711c0fcea919337e37d3238dd5972bd56068
* 6463de4a683c564f0b1d5fdac6bc9665a359ccae
* 76ed34ce0acc8286f91d296df2c531702fbb75aa
* fb373ad8e895fda6c5b4fbeb716ba50bd25a5132
* 086775bff6ec42059e0194c71c2140a153113ea5

**Comment by thaeli** [comment]
@bbkiwi fixed in PR #109

**Comment by AEFeinstein** [comment]
@AEFeinstein fixed more aggressively in #111
