### ISSUE TITLE
Linked Swadge Rings

### ISSUE THREAD

**Issue by bbkiwi** [AEFeinstein/Swadge-Devkit-Fw#11]
Hi Adam, 

I was unsure about doing this on my own, but I've got a friend, [Richard Jones](https://www.linkedin.com/in/richard-jones-28334782/), interested in working with me on this.  With his electronics and my maths, I think we can get this done :-)

**Summary**

- Swadges link together in a ring (or other configurations). 
- Light patterns in response to surrounding audio  or rhythmic  movement display on the linked collection. 
- Implement a simple game where each swadge can inject  light blasts into these patterns
that can be "moved" and/or "captured" by others using gestures and/or the buttons. 

**Technical Spec**
Will use wifi, leds, accelerometers (maybe OLED). 
We will develop a few helper functions to establish the network and  display
to the networked swages LEDs. 

**How to Test**
We would like a development kit. Gillian and Mark said they would send me some
2019 swadges to play with. I've not got any yet, but if they can be reprogrammed we could  use them to test the networking.

**Comment by AEFeinstein** [comment]
I'll use this ticket for the following two goals:
1. Extract prior year's peer to peer connection code from Reflector.
1. Expand the connection code to handle multiple simultaneous connections. This will require an adjustable RSSI connection threshold. Even though a collection of swadges will be a 'mesh' routing will not be automatically handled (i.e. you can only communicate with your immediate neighbors)

I think the networking is going to be the hard part of the ticket. Establishing the rules of the game is easier. Mocking the UI for connecting is medium.

**Comment by bbkiwi** [comment]
Just a few thoughts on the process of linking swadges.
1. Swadges go in link mode (from menu) and they flash blue
2. Two people stand side by side as AB
       A holds right button, while B holds left button (ie nearest buttons)
          while holding the swadges close, they connect and flash yellow say.
3. Other players in link mode can bring there swadges close to either end
     and they will link with them.
4. Eventually the ring will close and all will start flashing red say
5. Game play can begin.

**Comment by AEFeinstein** [comment]
The extraction of the prior connection code happened in #22 (this branch: https://github.com/AEFeinstein/Swadge-Devkit-Fw/tree/comm_protocol). The way it's written, you _should_ be able to have multiple simultaneous connections as long as each has a unique three-char ID (i.e. "lr1" and "lr2"). There's documentation here: https://github.com/AEFeinstein/Swadge-Devkit-Fw/blob/comm_protocol/docs/P2P_CONNECTION.md

You'd have to create the UI and orchestrate the crowd to each do their "lr1" pairing first, then their "lr2" pairing for a ring (or other shape). I don't think you can run the connection phase of both of them at the same time.

**Comment by AEFeinstein** [comment]
This is going to be shelved for a future Swadge where we can really advertise it ahead of time and set up an event during Magfest where Swadge owners can congregate and play
