### ISSUE TITLE
Tilted Tetris Mode

### ISSUE THREAD

**Issue by jt-moriarty** [AEFeinstein/Swadge-Devkit-Fw#15]
**Summary**
A single player game mode that plays like a simplified version of the classic game Tetris, using the accelerometer to move pieces left and right as they fall into place.

**Technical Spec**
This mode requires the screen in order to actually display the game, as well as the accelerometer for movement, and 2 mode specific buttons, one for piece rotation, and one for quick piece drop (or other useful Tetris mechanics). This mode will have a title screen, a game screen, and a high score / game over screen.
Wifi could be used to pull other nearby high scores for competitions, but this is just a possibility, and not something I want to guarantee at this time.

**UI**
Title Screen:
1 Button Starts the game.
(Optional/Possible) 1 Button opens High Scores. 
(Optional/Possible) Accelerometer can be used in this screen to tilt something as a way to demonstrate / practice that control before game start. 

Game Screen:
1 Button rotates the current piece.
Accelerometer used to tilt pieces left and right while they are falling.
(Optional/Possible) 1 Button used to instant drop pieces.
(Optional/Possible) 1 Button used to bank pieces / retrieve pieces from bank.
(Optional/Possible) LEDs, Sound, and Rumble can be used for various FX.

Game Over / High Score Screen:
(Optional/Possible) Accelerometer for score list scrolling.
1 Buttons exits and returns to Title screen.
(Optional/Possible) Use buttons to implement simple score name entry.

**How to Test**
A user can enter the mode, start a game, test that the controls work, end the game, and verify that they receive a score and can restart the game.

**Comment by AEFeinstein** [comment]
In general, I like this a lot. As far as the (optional) items, here are my thoughts:
* High scores - Locally, absolutely. Wifi, probably not. If anything, I'd like to encourage people physically showing scores to each other.
* Menu Accelerometer - Love the concept of teaching users this way. A simple 'ball' in the background would do it. Probably don't want to control the menu via accelerometer though.
* Tetromino bank - Probably not. NES Tetris didn't have one, and this requires a third button. I like rotate & drop as the two buttons
* Various FX - hardware depending, wouldn't be difficult in firmware.
* Name Entry - Would rather not, someone will write a bad thing 😞 

Also, the title and game over screens can be the same, but with different text written at the top (game title for the title, score for game over). Both would either go to the high score list or start a new game.

**Comment by jt-moriarty** [comment]
Ok, that all makes sense, can do!

**Comment by AEFeinstein** [comment]
It's done enough to close the ticket. Any more conversations'll be over Slack
