### ISSUE TITLE
Moving virtual ball on OLED and LEDs

### ISSUE THREAD

**Issue by bbkiwi** [AEFeinstein/Swadge-Devkit-Fw#19]
I've made new mode mode_roll testing the concept of moving a virtual ball in a circle with the accelerometer and having LEDs (that are in a ring that I imagine surrounds the circle) light up as it passes. The mode appears as ROLL in the menu. Set the intensity of the LEDs to low (as in dance mode), a ball on the OLED rolls as you tilt the swadge. 

It's a mash up of your demo and dance mode. It is not very efficient and duplicates much of the code from demo and dance so could share the routines. 
[https://youtu.be/N0L6-arMcYQ](url)
[https://github.com/bbkiwi/Swadge-Devkit-Fw/tree/masterB](url)

This branch incorporates the PR that fixes use of button 0, however it seems I have to hold button 0 down a bit longer to get into menu mode. Not sure why!

**Comment by bbkiwi** [comment]
Slight downside with button 0, if down hold down firmly when menubar gets to end sometimes jumps to first entry ie demo mode. 

In this branch also tweaked dance mode, and roll mode and colorchord mode to use NUM_LIN_LEDS so I can drive bigger rings than size 6.

**Comment by AEFeinstein** [comment]
I wonder if it's detecting a single press after reboot if the button is held? Should be easy to detect & fix, maybe by initializing button values to GPIO values rather than 0.

The other modes you tweaked NUM_LIN_LEDS for will likely be removed, but good that they've been fixed for now.

**Comment by bbkiwi** [comment]
1. The downside disappears if button 0 is for menu only.
2. Using NUM_LIN_LEDS was just an exercise, but I think it is a good idea to such defined parameters to make the code more flexible. 
3. mode_roll is just a concept test at this point to develop tools to use the accelerometer to move things. I’ve variations that can roll a virtual ball on the screen, so a game of solving a maze coukd be implemented.

**Comment by bbkiwi** [comment]
This is a more general comment related to having more common code. I wanted to reuse stuff from dance and demo, but found myself having to rename stuff (probably my lack of experience with c). 

Also here are comments from my friend Richard (who has not yet received a slack invite). Can he join the meeting this Thursday?

Hi Bill,

I had a few thoughts on the reflector game code that you showed me.
The game code that we looked through merged the game with the communications protocol.
This should be unpicked so that the game and the protocol are in separate files.
Then multiple games could use the same well tested protocol, and game simulations and game testing need not run on the hardware.
Maybe this has been done already?
Also the protocol needs to be adapted for large numbers of cooperating swadges.

**Comment by AEFeinstein** [comment]
Rolling a ball through a maze, just like this:
![image](https://user-images.githubusercontent.com/231180/62567494-48884100-b859-11e9-9d71-0da149cdc90c.png)

Don't worry about cross-mode code reuse for now. Dance and Demo will be deleted eventually.

To Richard, I know the communication protocol has to be extricated from the previous game code. It's on my own to-do list, but I'll make an official ticket for it. Adapting it for multiple simultaneous connections is a step after that, and trickier.

**Comment by bbkiwi** [comment]
I've just added an ODE solver to this branch (that anyone can use - found it on the web and required very little tweaking) and used it to simulate a circular pendulum. I will now model a rolling ball and use it to implement the maze!

**Comment by AEFeinstein** [comment]
The ball is moving around the maze quite well, so I'll call this done.
