### ISSUE TITLE
Infinite Runner

### ISSUE THREAD

**Issue by poplar** [AEFeinstein/Swadge-Devkit-Fw#27]
**Summary**
Single player mode where the user uses the two buttons to duck or jump, avoiding obstacles on the ground, ceiling, and in the air. 

**Technical Spec**
Standard infinite runner game - select one of 3 modes (easy - bottom only, medium - bottom and floating, hard - bottom, floating, and top). User is given a score rating on the distance they have covered, which is saved separately between modes and is shown before starting the game.

**UI**
The initial screen shows the game title, the modes to select, and the high score on each. 

**How to Test**
Ensure game can be run infinitely without obstacles, with obstacles and no collision physics.
Ensure patterns are fair and will not randomly become impossible to clear.
Ensure hit boxes work correctly.

**Comment by AEFeinstein** [comment]
Avoiding obstacles on the ground (jump) and ceiling (duck) make sense. I don't quite get the obstacles in the air.

I think it would be good for the runner to accelerate so each round gets harder over time. I like the difficulty adjusting the types of objects to avoid.

Feel free to use silly placeholder graphics, we can always touch them up later.

**Comment by AEFeinstein** [comment]
Maybe next year
