### ISSUE TITLE
Colormovement

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Swadge-Devkit-Fw#28]
**Summary**
Do cool stuff with LEDs, reacting the accelerometer data

**Technical Spec**
There are a number of ways to do reactive LEDs. We should test and see the following methods
1. Map [X, Y, Z] to [R, G, B]
1. Map [X, Y, Z] to [H, S, V]
1. Calculate the magnitude of [X, Y, Z] and feed it into colorchord as a low frequency, one dimensional signal (will likely need to modify colorchord to key off lower frequencies)
1. Run some sort of peak detection on the magnitude signal and react to spikes (fist bump mode)

**UI**
The LEDs should blink, duh.
The OLED should have some menu to display and select the current reaction mode.
One button should cycle modes, the other should cycle brightness.
Last year one button cycled sensitivity, but I don't think that's necessary here.

**How to Test**
Wave it around, see if looks cooler than cool (ice cold)

**Comment by AEFeinstein** [comment]
@bbkiwi if you play around with option 3 (colorchord) please post results here.

**Comment by bbkiwi** [comment]
Will do, but I won’t be able to look at this for the next 5 days as I’ll be away. 

1 and 2 are easy to try but I suspect will be a bit boring. 

Another option (which is easy to implement) relates to the rollMode as it is now in my branch mazeandroll. There is one virtual pendulum which is driven by movement and the leds mirror this movement by flashing red. The pendulum has a natural resonance. To create a more interesting display, model 3 pendulums (for rgb) each with different frequencies and/or driven by x,y, or z readings.

**Comment by AEFeinstein** [comment]
I think you're right for 1 & 2, but I still want to see them. I can probably write it up quickly and get a demo going.

The pendulum approach sounds interesting. Let your imagination run wild!

**Comment by bbkiwi** [comment]
35 mins before I leave for the airport. Just got a quick and dirty mod to do the pendulum approach. See branch rolllcolor. Just put up videos on slack. Have fun at the meeting!

**Comment by AEFeinstein** [comment]
Superseded by #66
