### ISSUE TITLE
Need to reduce RAM use

### ISSUE THREAD

**Issue by radionerd** [AEFeinstein/Swadge-Devkit-Fw#35]
Adding the maze code to a branch yields an out of heap error when selecting the largest maze.

RAM needs to be shared between interrupt code, cached code from flash, static variables, stack and heap. To get different modes to co-exist in RAM the solutions in order of least complexity could be:

1. Eliminate unnecessary RAM use eg constants and oversized arrays
2. Re-factor modes to use less RAM
3. Re-factor modes to use heap for large arrays
4. Split modes into separately loadable objects

Reducing the size of the i2sblock from 4000 to 6 and placing constants like fonts in flash may be sufficient to solve the problem for the 2020 Swadge.
An ordered report of RAM usage may be generated as follows:
```
$ cd firmware
$ make debug
$ grep "^3ff[0-9a-f].* 00000[1-9a-f]" image.map | sort -r -k2
Address     Size
3ffed24c 00000fa0 b i2sBlock
3ffe935c 0000092a D font_TomThumb
3ffe8a32 0000092a D font_Radiostars
3ffe8108 0000092a D font_IbmVga8
3ffef2f0 000006a8 B g_ic
3fff5c78 00000578 B wytop
3fff6fc8 00000578 B wybot
3fff7540 00000578 B wxright
3fff7c24 00000578 B wxleft
3fff68c8 00000578 B swytop
3fff6350 00000578 B swybot
3fff81b8 00000578 B swxright
3fff56fc 00000578 B swxleft
3ffeadd8 00000428 d impure_data
3ffeb87c 00000400 R snakeBackground
3ffec090 00000400 R mysteryStrings
3ffee288 00000400 B priorFb
3ffee688 00000400 B currentFb
3fff97e8 000003c0 B Sdatspace32BOut
3fff9248 000003c0 B Sdatspace32B
3fff8c40 000002a8 B tutorialGrid
3fff893c 000002a8 B tetradsGrid
3fff5454 000002a8 B nextMazeGrid
3fff518c 000002a8 B mazesGrid
3ffe9cb4 00000230 D danceTimers
3ffec536 00000200 R Ssinonlytable
3fff9068 000001e0 B Sdatspace32A
3fff4fc8 000001c0 B ref
3fff61f0 0000015e B ytop
3fff7ab8 0000015e B ybot
3fff6e58 0000015e B xright
3fff8730 0000015e B xleft
3ffeb5ac 00000110 R rotating_banana
3ffec9f8 00000108 r `two_over_pi`
3ffecba0 00000101 R _ctype_
3ffea1ac 00000100 D zTetradRotations
3ffea5ac 00000100 D tTetradRotations
3ffea2ac 00000100 D sTetradRotations
3ffea6ac 00000100 D oTetradRotations
3ffea3ac 00000100 D lTetradRotations
3ffea4ac 00000100 D jTetradRotations
3ffea7ac 00000100 D iTetradRotations
3fff0d00 00000100 B pmc
3ffef010 00000100 B event_TaskQueue
```

**Comment by AEFeinstein** [comment]
The fonts and some other data is declared `const`, which I guess the xtensa compiler doesn't place in read only memory. Looks like the easy solution may be to decorate that data with [`ICACHE_RODATA_ATTR`](https://arduino-esp8266.readthedocs.io/en/latest/PROGMEM.html) instead. I'll compile that and check the map file.

**Comment by AEFeinstein** [comment]
`ICACHE_RODATA_ATTR` has been added where appropriate and segfaults have been fixed for non-aligned ROM reads. Good job!
