### ISSUE TITLE
Do something musical

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Swadge-Devkit-Fw#38]
Lots of unknowns here, make something instrumenty with Dac's musical guidance

**Comment by bbkiwi** [comment]
Notes are selected by tilting to move a ball around a circle of tones. The note plays while a button is held down. A menu selects various options such as scale ( major, minor, pentatonic, etc). Can also have a continuous varying tone (eg swaney whistle). LEDs glow with color corresponding to the pitch within an octave like CC. It may be possible for a users song to be saved.

**Comment by AEFeinstein** [comment]
I'm going from vague memory here, but Dac's proposal was not based on a physics simulation. It was something like:
* Have the swadge beep continuous quarter notes
* Map X axis (roll) to note frequency
  * The frequencies would be a non-chromatic scale
  * There would be different scales selectable through a UI
* Map Y axis (pitch) to quarter note tempo
* Ignore Z axis (yaw)

**Comment by bbkiwi** [comment]
I like my idea better. Not really any physics modeling here, but positioning by tilting around the circle gives a simple visual indication of the note selected. As a musician myself I like control of the rhythm and pushing a button gives that control.

When is dac back?

**Comment by AEFeinstein** [comment]
When you said "moving a ball" I assumed it was with momentum and friction and the like. Guess I was wrong.

If you're tilting a bunch, you likely won't be able to see the display well. You can also display a ball on a 1D track if you only map one axis to frequency.

Dac should be back on Thursday.

**Comment by AEFeinstein** [comment]
Begin worked on in https://github.com/AEFeinstein/Swadge-Devkit-Fw/tree/swynth

**Comment by AEFeinstein** [comment]
Almost there. Still needs rhythms and maybe some tuning on how position is calculated.
