### ISSUE TITLE
Add some pads to circuit board

### ISSUE THREAD

**Issue by bbkiwi** [AEFeinstein/Swadge-Devkit-Fw#5]
**Summary**
Make it easy to add more LEDs and other audio input. I envision doing this
to use the swadge later to make flashy things. 

- Add pads to can add more LEDs
- Add audio in pads, or plug that disconnects mic

**Technical Spec**
For more LEDs need breakout to pads of RX, +5, +3.3, GND 
(I don't think there is any standard connectors for strips (and none for rings)
Audio in: not sure exactly where to add input.

I imagine anyone want to do this would reprogram the firmware, but (at least)
for some mode, it may be possible to have NUM_LIN_LEDS be a parameter that can
be changed.

**Comment by AEFeinstein** [comment]
Moved to https://github.com/AEFeinstein/Swadge-Devkit/issues/21
