### ISSUE TITLE
Joust mode

### ISSUE THREAD

**Issue by adangert** [AEFeinstein/Swadge-Devkit-Fw#9]
**Summary**
Multiple players can join and participate in a JS Joust like game mode, where players try to jostle each others swadges while keeping their own still

**Technical Spec**
The accelerator would be key for tracking movement, the wifi could also be used to connect players to determine who wins in the event that multiple people are tagged at the same time. 

**UI**
The screen and lights (and also hopefully a speaker) can be used to track the player state during the game, i.e. green: in the game and playing, red, and explosion sound: out of the game.

**How to Test**
2+ controllers can enter the game mode and start a game, then both can be shaken to make sure there is communication between the two.

**Comment by adangert** [comment]
Note, since there is possibility of no sound or vibration in the final swadges, FFA mode likely is not a great idea since players are unlikely to look at their own swadges to see if they have been knocked out or not. I think a much better game mode is Fight club mode, which can incorporate many players and has a clearly defined winner and loser each round. Rules can be found here: https://github.com/adangert/JoustMania/wiki/Extended-Rules#fight-club

**Comment by AEFeinstein** [comment]
Minimum two players is nice too. I suspect that while we can organize larger games, they'll be fewer self-organizing ones.

**Comment by adangert** [comment]
Add Single player practice mode.

**Comment by AEFeinstein** [comment]
It's done enough to close the ticket. Any more conversations'll be over Slack
