### ISSUE TITLE
Add LED FX When Snake Eats

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Swadge-Devkit-Fw#90]
Just a little blink or something, can be the same for critters and food.

Change goes around `startBuzzerSong(&critterSfx);` and `startBuzzerSong(&foodSfx);`

**Comment by thaeli** [comment]
Change committed in #94

**Comment by thaeli** [comment]
Better change in PR #110

**Comment by AEFeinstein** [comment]
Merged!
