### ISSUE TITLE
Joust: Speaker buzz after sound finishes playing

### ISSUE THREAD

**Issue by thaeli** [AEFeinstein/Swadge-Devkit-Fw#96]
**Expected Behavior**
After sound, silence.

**Actual Behavior**
After sound, continued quiet noise from speaker.

**Steps To Reproduce or What You Were Doing**
Play FFA Joust. Trigger the warning beep a bunch of times. Sometimes it will be silent after the beep completes, sometimes there's continued noise from the speaker. A subsequent beep will sometimes return it to silence after.

**Logs, Pictures, or Video**
I added some logging to hpa_timer.c and the SILENCE note is being properly invoked at the end of the sound. Not sure why it's not going silent. Sounds like an amp left on but we aren't using an amp!

**Comment by AEFeinstein** [comment]
@thaeli try applying this patch and see what you hear. It explicitly drives the buzzer high when quiet so the voltage on both sides of the buzzer should be high and hopefully not buzzy.

[bzr.txt](https://github.com/AEFeinstein/Swadge-Devkit-Fw/files/3965098/bzr.txt)

**Comment by thaeli** [comment]
That patch makes the noise happen ALL the time instead of just sometimes.

**Comment by thaeli** [comment]
Woot, "false" instead of "true" fixed it.

**Comment by AEFeinstein** [comment]
That makes sense, actually. The other half of the buzzer is grounded, not at 3V. Good catch, and next time i should consult the schematic before hastily writing a patch.
![image](https://user-images.githubusercontent.com/231180/71006522-6c834b00-20b3-11ea-9bc5-0c6a84f4b952.png)
