### ISSUE TITLE
Gallery tweaks

### ISSUE THREAD

**Issue by thaeli** [AEFeinstein/Swadge-Devkit-Fw#97]
* Add additional gallery images
* Add additional ringtones
* Make and add credits image @dac

**Comment by AEFeinstein** [comment]
* Ringtones added in 8d628ca3f17837f3b8ad51b08a4e69f151210ec9
* Gallery images to be added tomorrow, after they're collected and checked by dac

**Comment by AEFeinstein** [comment]
Gifs added in 
* 12a8cb189f1eb54ab87eec9b959071d382288dfd
* f138f13e4bd3996c70afbdd49e69df67afd91238
